WEB_BASE/Controllers/ModuleController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using Microsoft.AspNet.Identity.Owin;
using Trirand.Web.Mvc;
using WEB_BASE.Models;
using WEB_BASE.Repository;


namespace WEB_BASE.Controllers
{
    [Authorize]
    public class ModuleController : Controller
    {
        private readonly UnitOfWork _unitOfWork = new UnitOfWork();
        private readonly Util _util = new Util();
        private ApplicationUserManager _userManager;
        List<JQTreeNode> _checkedNodes = new List<JQTreeNode>();


        public ModuleController()
        {
        }

        public ModuleController(ApplicationUserManager userManager)
        {
            _userManager = userManager;
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
        }

        // GET: Module
        public async Task<ActionResult> Index()
        {
            return View(await _unitOfWork.ModulesRepository.DbSet.ToListAsync());
        }

        // GET: Module/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var module = await _unitOfWork.ModulesRepository.DbSet.FindAsync(id);//db.Modules.FindAsync(id);
            if (module == null)
            {
                return HttpNotFound();
            }
            return View(module);
        }

        // GET: Module/Create
        public ActionResult Create()
        {
            ViewBag.Icon = new SelectList(_util.GetAllIcons().OrderBy(i => i.Icon), "Icon", "Icon");
            var listMod = new List<Module> {new Module {ParentModuleId = null, ModuleName = ""}};
            listMod.AddRange(_unitOfWork.ModulesRepository.DbSet.Where(m => m.ParentModuleId == null));
            ViewBag.ParentModuleId =
                new SelectList(
                    listMod,
                    "ParentModuleId", "ModuleName", "");
            return View();
        }

        // POST: Module/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ModuleId,ModuleName,Controller,Action,Icon,ParentModuleId")] Module module)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.ModulesRepository.Insert(module);
                await _unitOfWork.ModulesRepository.Context.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            ViewBag.Icon = new SelectList(_util.GetAllIcons().OrderBy(i => i.Icon), "Icon", "Icon");
            var listMod = new List<Module> { new Module { ParentModuleId = null, ModuleName = "" } };
            listMod.AddRange(_unitOfWork.ModulesRepository.DbSet.Where(m => m.ParentModuleId == null));
            ViewBag.ParentModuleId =
                new SelectList(
                    listMod,
                    "ParentModuleId", "ModuleName", "");

            return View(module);
        }

        // GET: Module/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Module module = await _unitOfWork.ModulesRepository.DbSet.FindAsync(id);
            ViewBag.Icon = new SelectList(_util.GetAllIcons().OrderBy(i => i.Icon), "Icon", "Icon");
            if (module == null)
            {
                return HttpNotFound();
            }
            return View(module);
        }

        // POST: Module/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ModuleId,ModuleName,Controller,Action,Icon,ParentModuleId")] Module module)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.ModulesRepository.Context.Entry(module).State = EntityState.Modified;
                await _unitOfWork.ModulesRepository.Context.SaveChangesAsync();

                return RedirectToAction("Index");
            }
            return View(module);
        }

        // GET: Module/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Module module = await _unitOfWork.ModulesRepository.DbSet.FindAsync(id);
            if (module == null)
            {
                return HttpNotFound();
            }
            return View(module);
        }

        // POST: Module/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Module module = await _unitOfWork.ModulesRepository.DbSet.FindAsync(id);
            _unitOfWork.ModulesRepository.Delete(module);
            await _unitOfWork.ModulesRepository.Context.SaveChangesAsync();

            return RedirectToAction("Index");
        }

        // GET: Module/ManageAccess
        public ActionResult ManageAccess()
        {
            ViewBag.UserId = new SelectList(UserManager.Users.ToList(), "Id", "Name");
            return View();
        }

        // POST: Module/ManageAccess
        [HttpPost]
        public ActionResult ManageAccess(ManageAccessViewModels model)
        {
            ViewBag.UserId = new SelectList(UserManager.Users.ToList(), "Id", "Name");

            if (!String.IsNullOrEmpty(model.UserId))
            {
                if (model.CheckBoxesTreeView_checkedState != "[]")
                {
                    try
                    {
                        //pegar acessos selecionados
                        var deserialize = new JavaScriptSerializer();
                        _checkedNodes = deserialize.Deserialize<List<JQTreeNode>>(model.CheckBoxesTreeView_checkedState);

                        //Deletar todos os acessos do usuários
                        _unitOfWork.ModuleUserAccessRepository.DbSet.RemoveRange(
                            _unitOfWork.ModuleUserAccessRepository.DbSet.Where(a => a.UserId == model.UserId));

                        //Inserindo os novos acessos
                        foreach (var access in _checkedNodes.Select(chk => new ModuleUserAccess { ModuleId = int.Parse(chk.Value), UserId = model.UserId }))
                        {
                            _unitOfWork.ModuleUserAccessRepository.Insert(access);
                        }

                        //Salvar alterações
                        _unitOfWork.ModuleUserAccessRepository.Context.SaveChanges();
                    }
                    catch (Exception)
                    {
                        TempData["error"] = "Erro ao efetuar a liberação dos módulos.";
                        return View();
                    }
                }
                else
                {
                    TempData["error"] = "Favor selecionar os módulos a serem liberados.";
                    return View(model);
                }
            }
            else
            {
                TempData["error"] = "Favor selecionar o usuário.";
                return View(model);
            }
            TempData["success"] = "Liberação efetuada com sucesso.";
            return View();
        }

        public JsonResult TreeView_CheckBoxes_DataRequested()
        {
            var tree = new JQTreeView();

            //var userId = User.Identity.GetUserId();
            var module = _unitOfWork.ModulesRepository.DbSet.Where(m => m.ParentModuleId == null).ToList();
            //from mod in _unitOfWork.ModulesRepository.DbSet
            //join modAccess in _unitOfWork.ModuleUserAccessRepository.DbSet on mod.ModuleId equals modAccess.ModuleId
            //where modAccess.UserId == userId
            //select mod;
            //var module = mod.ToList();
            var nodes = new List<JQTreeNode>();
            foreach (var mod in module)
            {
                nodes.Add(new JQTreeNode
                {
                    Text = mod.ModuleName,
                    Value = mod.ModuleId.ToString(CultureInfo.InvariantCulture),
                    Expanded = true
                });

                foreach (var subMod in mod.SubModules)
                {
                    var secondNode = nodes.Find(n => n.Text == mod.ModuleName);
                    secondNode.Nodes.Add(new JQTreeNode { Text = subMod.ModuleName, Value = subMod.ModuleId.ToString(CultureInfo.InvariantCulture) });
                }
            }

            SetCheckedNodes(nodes);

            return tree.DataBind(nodes);
        }

        public void SetCheckedNodes(List<JQTreeNode> allNodes)
        {
            var checkedNodes = Session["checkedNodes"] as List<JQTreeNode>;
            if (checkedNodes != null)
            {
                var tree = new JQTreeView();
                var allNodesFlat = tree.GetAllNodesFlat(allNodes);

                foreach (JQTreeNode node in allNodesFlat)
                {
                    var matchedCheckedNode =
                        checkedNodes.Find(checkedNode => checkedNode.Value == node.Value);
                    if (matchedCheckedNode != null)
                        node.Checked = true;
                }
            }
        }
    }
}

WEB_BASE/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using WEB_BASE.Models;
using WEB_BASE.Repository;
using PagedList;

namespace WEB_BASE.Controllers
{
    [Authorize]
    public class ProductController : Controller
    {
        private readonly UnitOfWork _unitOfWork = new UnitOfWork();

        // GET: Products
        public ActionResult Index([Bind(Include = "SearchString, SortOrder, CurrentFilter, Page")] string searchString, string sortOrder, string currentFilter, int? page)
        {
            if (!_unitOfWork.ValidUserAccess((List<Module>) Session["UserAccess"],
                                             ControllerContext.RouteData.Values["action"].ToString(),
                                             ControllerContext.RouteData.Values["controller"].ToString(),
                                             User.Identity.GetUserId()))
            {
                Session.Add("UrlDenied", ControllerContext.RouteData.Values["controller"] + "/" + ControllerContext.RouteData.Values["action"]);
                return RedirectToAction("AccessDenied", "Home");
            }

            ViewBag.NameParam = String.IsNullOrEmpty(sortOrder) ? "Name_Desc" : "";
            ViewBag.DateParam = sortOrder == "Date" ? "Date_Desc" : "Date";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            ViewBag.CurrentSort = sortOrder;

            var products = _unitOfWork.ProductsRepository.DbSet
                .OrderByDescending(p => p.ProductName)
                .Include(p => p.Category)
                .Select(p => new ProductViewModels
                {
                    ProductId = p.ProductId,
                    ProductCode = p.ProductCode,
                    ProductName = p.ProductName,
                    UnitPrice = p.UnitPrice,
                    CreatedBy = p.CreatedBy,
                    CreationDate = p.CreationDate,
                    CategoryName = p.Category.CategoryName,
                }
                );

            if (!String.IsNullOrEmpty(searchString))
            {
                products = products.Where(p => p.ProductName.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "Name_Desc":
                    products = products.OrderByDescending(p => p.ProductName);
                    break;
                case "Date":
                    products = products.OrderBy(p => p.CreationDate);
                    break;
                case "Date_Desc":
                    products = products.OrderByDescending(p => p.CreationDate);
                    break;
                default:
                    products = products.OrderBy(p => p.ProductName);
                    break;
            }

            const int pageSize = 5;
            var pageNumber = page ?? 1;

            if (Request.IsAjaxRequest())
            {
                System.Threading.Thread.Sleep(500);
                return PartialView("_ListProducts", products.ToPagedList(pageNumber, pageSize));
            }

            return View(products.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult AutoComplete(string term)
        {
            var produtcsName = _unitOfWork.ProductsRepository.DbSet


                .Where(a => a.ProductName.StartsWith(term))
                .Take(10)
                .Select(a => new
                {
                    label = a.ProductName
                });

            return Json(produtcsName, JsonRequestBehavior.AllowGet);
        }

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                //return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                return RedirectToAction("Error", "Home");
            }
            Product productsModels = _unitOfWork.ProductsRepository.GetById(id);
            if (productsModels == null)
            {
                return HttpNotFound();
            }
            return View(productsModels);
        }

        // GET: Products/Create
        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(_unitOfWork.ProductsCategoryRepository.DbSet, "CategoryId", "CategoryName");
            if (Request.IsAjaxRequest())
            {
                return PartialView("_FormCreate");
            }
            return View();
        }

        // POST: Products/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ProductId,ProductCode,ProductName,UnitPrice,CategoryId")] Product productsModels)
        {
            if (ModelState.IsValid)
            {
                productsModels.CreationDate = DateTime.Now;
                productsModels.CreatedBy = User.Identity.GetUserId();

                _unitOfWork.ProductsRepository.Insert(productsModels);
                _unitOfWork.ProductsRepository.Commit();

                ViewBag.CategoryId = new SelectList(_unitOfWork.ProductsCategoryRepository.DbSet, "CategoryId", "CategoryName");
                return PartialView("_CreateSuccess");
            }

            ViewBag.CategoryId = new SelectList(_unitOfWork.ProductsCategoryRepository.DbSet, "CategoryId", "CategoryName");
            return PartialView("_FormCreate", productsModels);
        }

        // GET: Products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product productsModels = _unitOfWork.ProductsRepository.GetById(id);
            if (productsModels == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(_unitOfWork.ProductsCategoryRepository.DbSet, "CategoryId", "CategoryName");
            return View(productsModels);
        }

        // POST: Products/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ProductId,ProductCode,ProductName,UnitPrice,CategoryId,CreatedBy,CreationDate")] Product productsModels)
        {
            if (ModelState.IsValid)
            {
                productsModels.UpdatedDate = DateTime.Now;
                productsModels.UpdatedBy = User.Identity.GetUserId();

                _unitOfWork.ProductsRepository.Update(productsModels);
                _unitOfWork.ProductsRepository.Commit();

                return RedirectToAction("Index");
            }
            ViewBag.CategoryId = new SelectList(_unitOfWork.ProductsCategoryRepository.DbSet, "CategoryId", "CategoryName");
            return View(productsModels);
        }

        // GET: Products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product productsModels = _unitOfWork.ProductsRepository.GetById(id);
            if (productsModels == null)
            {
                return HttpNotFound();
            }
            return View(productsModels);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product productsModels = _unitOfWork.ProductsRepository.GetById(id);

            _unitOfWork.ProductsRepository.Delete(productsModels);
            _unitOfWork.ProductsRepository.Commit();

            return RedirectToAction("Index");
        }
    }
}

WEB_BASE/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>

    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/bootstrap")

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    @Html.Partial("_Menu")
    <div id="content" class="container body-content">
        @RenderBody()
    </div>
    
    <div class="container-fluid footer">
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Meu Aplicativo ASP.NET - Criado por Jonatas Fódãoo</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/otf")

    @RenderSection("scripts", false)
</body>
</html>

WEB_BASE/Views/Shared/_LayoutAuth.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>
    <link rel="stylesheet" type="text/css" href="~/Content/themes/redmond/jquery-ui.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/themes/ui.jqtreeview.css" />

    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/bootstrap")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @Html.Partial("_Menu")
    <div class="container body-content">
        <div class="row">
            <div id="menu_lateral">
                @Html.Partial("_SideMenu")
            </div>
            <div class="col-md-9 col-sm-9">
                <div id="conteudo">
                    @RenderBody()
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid footer">
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Meu Aplicativo ASP.NET - Criado por Jonatas Fódãoo</p>
        </footer>
    </div>


    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/otf")
    @RenderSection("scripts", false)
</body>
</html>

WEB_BASE/Views/Shared/_Menu.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Exemplos de Implementações", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse" role="navigation">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Início", "Index", "Home")</li>
                <li>@Html.ActionLink("Sobre", "About", "Home")</li>
                <li>@Html.ActionLink("Contato", "Contact", "Home")</li>
                <li>@Html.ActionLink("Produtos", "Index", "Product")</li>
                <li>@Html.ActionLink("Módulos", "Index", "Module")</li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>

WEB_BASE/Views/Shared/_SideMenu.cshtml
@using Microsoft.AspNet.Identity
@using WEB_BASE.Repository
@{
    var unitOfWork = new UnitOfWork();
    var userId = User.Identity.GetUserId();
    
    var query = from mod in unitOfWork.ModulesRepository.DbSet          
        join modAccess in unitOfWork.ModuleUserAccessRepository.DbSet on mod.ModuleId equals modAccess.ModuleId
        where modAccess.UserId == userId
              && mod.ParentModuleId == null
        select mod;
       
    var module = query.ToList();
    var i = 1;
}
@if (module.Any())
{
    <div class="col-sm-3 col-md-3">
        <div class="panel-group" id="accordion">
            @foreach (var mod in module)
            {
                string id;
                string idAux;
                {
                    id = "collapse" + i;
                    idAux = "#" + id;
                }

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="@idAux">
                                @{
                                    var icon = "glyphicon " + mod.Icon;
                                }
                                <span class="@icon">
                                </span>@mod.ModuleName
                            </a>
                        </h4>
                    </div>
                    <div id="@id" class="panel-collapse collapse">
                        <div class="panel-body">
                            <table class="table">
                                @{
                                    var modCopy = mod;
                                    var subQuery = from sm in mod.SubModules
                                        join modAccess in unitOfWork.ModuleUserAccessRepository.DbSet on sm.ModuleId equals modAccess.ModuleId
                                        where modAccess.UserId == userId
                                              && sm.ParentModuleId == modCopy.ModuleId
                                        select sm;
                                    var subModule = subQuery.ToList();
                                }
                                @foreach (var subMod in subModule.OrderBy(m => m.ModuleName))
                                {                 
                                    <tr>
                                        @{icon = "glyphicon " + subMod.Icon;}
                                        <td>
                                            <span class="@icon"></span>
                                            @Html.ActionLink(subMod.ModuleName, subMod.Action, subMod.Controller)
                                            @*@Ajax.ActionLink(subMod.ModuleName, subMod.Action, subMod.Controller,
    new AjaxOptions
    {
        HttpMethod = "Get",
        InsertionMode = InsertionMode.Replace,
        UpdateTargetId = "listUsers",
        OnBegin = "processing.showPleaseWait();",
        OnComplete = "processing.hidePleaseWait();",
        OnFailure = "showMessage('Erro', 'Ocorreu um erro ao processar a solicitação!', 'danger');",
    })*@
                                        </td>
                                    </tr>
                                }
                            </table>
                        </div>
                    </div>
                </div>
                {
                    i++;
                }
            }
        </div>
    </div>
}